### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/AutoTransformR#8]
Hello,

Thanks for your milestone 01 submission. I just have some comments below,

- Good job on using `Roxygen2` package in generating the function documentation templates.
- Why you didn't add `num_images` as a parameter in `mirror.R`?
- You should define `Path` inside the test scripts. Assign `Path` to an arbitrary image path inside the project location.
-  Change "img/Path" in the line below accordingly after you assign a value to "Path". 
```
expect_error(mirror("img/Path"), "Incorrect directory/file not found")
```
- There is a python code chunk inside of the `test_mirror.R`.
```
  test_img = skimage.io.imread(test_image)
  returned_arr_1a = pre.mirror(test_img, "horizontal")  # should return 1 image
  returned_arr_1b = pre.mirror(test_img, "vertical")  # should return 1 image
  returned_arr_2a = pre.mirror(test_img, "all")  # should return 2 images
  returned_arr_2b = pre.mirror(test_img)  # all is default, should return 2 images
```
- You should assign a value to `test_image`.
- 'expect_is' should be in the format `expect_is(object,class)` not `expect_is(object == value). Example: `expect_is(string,"character")`. Refer to the `testthat` (documentation)[https://cran.r-project.org/web/packages/testthat/testthat.pdf].
- These same comments are applicable to `test_rotate` and `test_translate` as well.

Thank you!

**Comment by alyciakb** [comment]
- `num_images` is irrelevant in the mirror function because the function offers the user the option to mirror it in the vertical or horizontal directions or both. Therefore, they will be returned a set number of photos based on the direction of the mirroring.
- As this week was focussed on Python, we updated the test files in Python to include a sample image that is passed into the test scripts and updated the input of the tests accordingly. We will do the same with R next week.
- the other errors and Python code in `test_mirror.R` will be changed and fixed next week as we work on developing the R function. 

Thanks!
